services:
  nginx:
    image: ${DOCKER_USERNAME}/mernchess_frontend:latest
    container_name: mern_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/nginx/nginx.conf:ro
      - ./nginx/conf.d/prod.conf:/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/nginx/certs:ro

    depends_on:
      - backend
    restart: always

  backend:
    image: ${DOCKER_USERNAME}/mernchess_backend:latest
    container_name: mern_backend

    expose:
      - "5000"

    restart: always
